config/routes.rb
Rails.application.routes.draw do

  root 'books#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :edit, :update, :index]
  get 'about' => 'books#about'
#doでendは結びつくので、endは一つでおk
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

   belongs_to :user
   validates :book_comment, length: { in: 1..200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable




         has_many :books, dependent: :destroy
         attachment :profile_image

         validates :name, presence: true
         validates :name, length: { in: 2..20 }
         validates :email, presence: true
         validates :introduction, length: { maximum: 50 }



         #登録時にメールアドレスを不要とする
  def email_required?
    false
  end

  def email_changed?
    false
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authenticate_user!, :except=>[:about,:index]
before_action :configure_permitted_parameters, if: :devise_controller?

 
def after_sign_in_path_for(resource)
    user_path(@user.id) # ログイン後に遷移するpathを設定
  end

  protected
  
  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
   devise_parameter_sanitizer.permit(:sign_in, keys: [:name,:password])

   end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :correct_user, only: [:edit, :update]

   def new
   	@book = Book.new
   	@books = Book.all
    @user = current_user

   end

   def create
   	@book = Book.new(book_params)
   	@book.user_id = current_user.id #asotiation
      if @book.save
       flash[:notice] = "Your post was successfully created"
       redirect_to book_path(@book.id)
      else
       @user = current_user
       # @book = Book.new(book_params)
       @books = Book.all
       render :new

   end
   end

   def index
   	 @books = Book.all
     @book = Book.new
     @user = current_user
   end

   def show
     @book = Book.find(params[:id])
     @user = current_user
     @books = Book.new
   end

   def destroy
   	@book = Book.find(params[:id])
   	@book.destroy
   	redirect_to '/books/new'
   end

   def edit
     @book = Book.find(params[:id])
   end

   def update
     @book = Book.find(params[:id])
     @book.update(book_params)
     redirect_to book_path(@book.id)
   end


   def about
   end

   private
   
   def book_params
   params.require(:book).permit(:book_title, :book_comment)
   end

   private
  def correct_user
    book = Book.find(params[:id])
    if current_user.id != book.user.id
      redirect_to root_path
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@books = @user.books.all
    @book = Book.new
    @users = current_user

  end

  def edit
  	@user = User.find(params[:id])
    
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
  	  redirect_to user_path(@user.id)
    else
      # @user = current_user ←これがあるとバリデーションが通っちゃう
      @books = Book.all
      @book = Book.new
      render :edit

    end

  end


def index #下記のメソッドで、user.index.htmlを表示する
  @books = Book.all
  @book = Book.new
  @user = current_user
  @users = User.all
end




  private
  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/about.html.erb
</div><div class="col-lg-2" style="background-color: white;">
        </div>

      <div class="col-lg-10">
        <h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>

app/views/books/edit.html.erb
<div class="row">
        <div class="col-md-4 col-md-offset-4">
              <div class="post">
                <h1>New book</h1>
                  <%= form_for(@book) do |f| %>
                <h4>Editing Book</h4>
                  <%= f.text_field :book_title , class: "book_title col-lg-12"%>
                <h4>Opinion</h4>
                   <%= f.text_area :book_comment, class: "book_body  col-lg-12" %>
                   <br>
                   <br>
                   <p> </p>
                <%= f.submit 'Create Book',class: 'btn btn-primary col-lg-12' %>
                
                <p> <%= link_to'back', :back, class:"back"%>|<%= link_to'show', book_path(@book.id), class:"book_#{@book.id}"  %></p>

                <% end %>

              </div>
            </div>

app/views/books/index.html.erb
  <div class="container"> <!-- ここを追加 -->
      <div class="row">   <!-- ここを追加 -->
        


</div>
</div><div class="col-lg-3" style="background-color: white;">
        </div>

      <div class="col-lg-9">
        <h2>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h2>

         <p>
          In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><b>Bookers,</b><br>
          you can share and exchange your opinions , inpressions , and emotions<br>about varioius books!
         </p>
      </div>


<div class="row">
        <div class="col-md-4 col-md-offset-4">


    
<%= link_to 'Log in',new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>
<%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
</div>
</div>

app/views/books/new.html.erb
<h3>Books</h3>
<table>
<thead>
<tr>
<th>title</th>
<th>body</th>
<th></th>
</tr>
</thead>

<tbody>
<td>
<%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %>
</td>

<% @books.each do |book| %>
<tr>
<td>
<%= book.book_title %>
</td>
<td>
<%= book.book_comment %>
</td>
<td>


	<%#なぜ@siteじゃないのか？？ なぜclassを入れるのか%>
<%= link_to "show", book_path(book.id),class:"show_#{book.id}" %>

<%= link_to "destroy", book_path(book.id), method: :delete, class:"destroy_#{book.id}",data: {confirm:'Are you sure?？'} %>


</td>
</tr>
<% end %>
</tbody>
</table>


<div class="box2">
<h1>New book</h1>

<%= form_for(@book) do |f| %>

<h4>Title</h4>
<%= f.text_field :book_title , class:"book_title"%>

<h4>Body</h4>
<%= f.text_area :book_comment, class:"book_body" %>

<%= f.submit '投稿' %>

<% end %>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

  <div class="container"> <!-- ここを追加 -->
    <div class="row">
      <div class="col-lg-3">
        <h2 >User info</h2>
          <div class = "profile_image">
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
          </div>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
          <table class="table table-striped">
            <tr><td>NAME<td><%= @user.name %>
            <tr><td>Introduction<td> <%= @user.introduction %>
          </table>
            <%= link_to '', edit_user_path(@user.id), class: 'btn btn-default glyphicon glyphicon-wrench col-lg-12 edit_user_#{@user.id}' %>
              <div class="post">
                <h1>New book</h1>
                  <%= form_for(@books) do |f| %>
                <h4>Title</h4>
                  <%= f.text_field :book_title , class: "book_title col-lg-12"%>
                <h4>Opinion</h4>
                   <%= f.text_area :book_comment, class: "book_body  col-lg-12" %>
                   <br>
                   <br>
                   <p> </p>
                <%= f.submit 'Create Book',class: 'btn btn-primary col-lg-12' %>
                <% end %>
              </div>
      </div>
   
      <div class="col-lg-9">  <!-- ここを追加 -->
        <table class="table table-default">
            <h2>Book detail</h2>
        <thead>
          <th></th>
           <th></th>
          <th></th>
        </thead>


      <tbody>
       <td>
         <%= link_to attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",:size => "40x40" %>
       <br>
       <span><%= link_to @book.user.name, user_path(@book.user.id), class: "user_#{@user.id}" %>
       </td>

      
       <td>
        <%= link_to @book.book_title, book_path(@book.id),class: "book_#{@book.id}" %>
       </td>
       <td></td>
       <td>
         <%= @book.book_comment %>
      </td>
      <td></td>
       <td>
        <% if @user.id == @book.user.id %>
        <%= link_to "edit", edit_book_path(@book), class:"label label-success edit_book_#{@book.id}" %>
      </td>
      <td>
        <%= link_to "destroy", book_path(@book), method: :delete, class:"label label-danger destroy_#{@book.id}",data: {confirm:'Are you sure?？'} %>
      </td>
      <% end %>
       <td></td>
     </tbody>
</table>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"><span>Bookers</span></a>
        </div>
       
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to ' Home',user_path(current_user),class: 'home glyphicon glyphicon-home' %></li>
          <li><%= link_to ' Users',users_path,class: 'users glyphicon glyphicon-user' %></li>
          <li><%= link_to ' Books', "/books/new",class: 'books glyphicon glyphicon-book'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete,class: 'logout glyphicon glyphicon-log-out' %></li>
        <% else %>
          <li><%= link_to ' Home',root_path, class: 'home glyphicon glyphicon-home' %></li>
          <li><%= link_to ' About',"/about",class: 'about glyphicon glyphicon-link' %></li>
          <li><%= link_to ' sign up', new_user_registration_path,class: 'sign_up glyphicon glyphicon-edit' %></li>
          <li><%= link_to ' login', new_user_session_path ,class: 'sign_in glyphicon glyphicon-log-in'%></li>
        <% end %>
      </ul>
     </div>
    </nav>








    <%= yield %>
  </body>

</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>Error</h2>
      <ul>

      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
         <div class="container"> <!-- ここを追加 -->
    <div class="row">   <!-- ここを追加 -->
    
          <div class="col-lg-1">

          </div>

                  <div class="col-lg-11">

                                <h2 class="form-header-title">User info</h2>
                            
                            
                              <%= form_for(@user) do |f| %>
                               
                               <div style="display:inline-flex"><b>Name</b>
                                  <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
                                   </div>
                                     <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
                             

                                  <p><b>Image</b></p>
                                
                                 <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
                                 <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form user_image" %>
                               
                               <br>


                               <label class="control-label sr-only" for="inputEmail">Name</label>

                               <br>
                               
                               <div style="display:inline-flex">
                                <br>

                                <b>Introduction</b>
                                  <%= f.text_area :introduction, autofocus: true, class:"form-control introduction", id:"inputIntroduction", placeholder:"introduction"%>
                                </div>
                                <br>


                            <br>
                            <%= f.submit 'Update User',class: 'btn btn-default col-lg-2' %>
                            <% end %>
      </div>

  </div>
</div>

          

app/views/users/index.html.erb
<div class="container"> <!-- ここを追加 -->
    <div class="row">   <!-- ここを追加 -->
    
          <div class="col-lg-3">

               <h2 >User info</h2>

                <div class = "profile_image">
                  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
                </div>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
              <table class="table table-default">
                 <tr><td>NAME<td><%= @user.name %>
                 <tr><td>Introduction<td> <%= @user.introduction %>
              </table>

              <%= link_to '', edit_user_path(@user.id), class: 'btn btn-default glyphicon glyphicon-wrench col-lg-12 edit_user_#{@user.id}' %>
              



              <div class="post">
                <h1>New book</h1>

                 <%= form_for(@book) do |f| %>

                 <h4>Title</h4>
                   <%= f.text_field :book_title , class: "book_title col-lg-12"%>

                 <h4>Opinion</h4>
                   <%= f.text_area :book_comment, class: "book_body  col-lg-12" %>

                   <br>
                   <br>
                   <p> </p>
                    <%= f.submit 'Create Book',class: 'btn btn-primary col-lg-12' %>
                  

                   

                   <% end %>
              </div>
          </div>

             <h2>Users</h2>

    <div class="col-lg-9">  <!-- ここを追加 -->
      <table class="table table-default">
        <thead>
          <th>image</th>
           <th>name</th>
        </thead>

    <tbody>
        

       <% @users.each do |user| %>
     <tr>
       <td>
         <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" ,:size => "40x40" %>
       </td>
       <td>
         <%= user.name %>
       </td>
       <td>


  
            <%= link_to "show", user_path(user.id),class:"show_#{user.id}" %>

            
       </td>
       <td></td>
      <% end %>
     </tbody>
</table>
</div>


</div>
</div>

app/views/users/show.html.erb
  
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>Error</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>




  <div class="container"> <!-- ここを追加 -->
    <div class="row">   <!-- ここを追加 -->
    
          <div class="col-lg-3">

               <h2 >User info</h2>

                <div class = "profile_image">
                  <%= attachment_image_tag @users, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
                </div>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
              <table class="table table-default">
                 <tr><td>NAME<td><%= @users.name %>
                 <tr><td>Introduction<td> <%= @users.introduction %>
              </table>

              <%= link_to '', edit_user_path, class: 'btn btn-default glyphicon glyphicon-wrench col-lg-12 edit_user_#{@user.id}' %>
              


              <div class="post">
                <h1>New book</h1>

                 <%= form_for(@book) do |f| %>

                 <h4>Title</h4>
                   <%= f.text_field :book_title , class: "book_title col-lg-12"%>

                 <h4>Opinion</h4>
                   <%= f.text_area :book_comment, class: "book_body  col-lg-12" %>

                   <br>
                   <br>
                   <p> </p>
                    <%= f.submit 'Create Book',class: 'btn btn-primary col-lg-12' %>
                  

                   

                   <% end %>
              </div>
          </div>



    <div class="col-lg-9">  <!-- ここを追加 -->
      <table class="table table-default">
          <h2>Books</h2>
         <thead>
          <th></th>
           <th>Title</th>
          <th>Opinion</th>
        </thead>

    <tbody>
       <% @books.each do |book| %>
     <tr>
       <td>
         <%=link_to attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",:size => "40x40" %>
       </td>
       <td>
          <%= link_to book.book_title, book_path(book.id), class: 'book_#{@book.id}'  %>
       </td>
       <td>
         <%= book.book_comment %>
      </td>
       <td>


  
            
       </td>
       <td></td>
      <% end %>
     </tbody>
</table>
</div>


</div>
</div>